#Funciones con Arrays

In [1]:
import numpy as np  # Importar la biblioteca NumPy

# Lista de números que se convertirá en un array
lista = [1, 2, 3, 4, 5]  # Lista original

# Convertir la lista a un array de NumPy
array = np.array(lista)  # Crear un array a partir de la lista

# Imprimir el array resultante
print("Array de NumPy:", array)

# Operaciones con el array
# 1. Sumar un valor a cada elemento del array
array_sumado = array + 10  # Sumar 10 a cada elemento
print("Array después de sumar 10:", array_sumado)

# 2. Multiplicar cada elemento del array por un valor
array_multiplicado = array * 2  # Multiplicar por 2
print("Array después de multiplicar por 2:", array_multiplicado)

# 3. Calcular la media del array
media = np.mean(array)  # Calcular la media
print("Media del array:", media)

# 4. Filtrar elementos mayores que un valor
filtro = array[array > 3]  # Filtrar elementos mayores que 3
print("Elementos del array mayores que 3:", filtro)

# 5. Cambiar la forma del array (reshape)
array_reshaped = array.reshape((5, 1))  # Cambiar la forma del array a una columna
print("Array reshaped (5x1):\n", array_reshaped)

Array de NumPy: [1 2 3 4 5]
Array después de sumar 10: [11 12 13 14 15]
Array después de multiplicar por 2: [ 2  4  6  8 10]
Media del array: 3.0
Elementos del array mayores que 3: [4 5]
Array reshaped (5x1):
 [[1]
 [2]
 [3]
 [4]
 [5]]


In [5]:
lista = [[1,2,3],[4,5,6],[7,8,9]]
array = np.array(lista)
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#Funciones Numpy arrays - arange, zeros, ones, linspace, eye

In [7]:
import numpy as np  # Importar la biblioteca NumPy

# 1. Crear un array con `arange`
# `arange(start, stop, step)` crea un array con valores en un rango especificado.
array_arange = np.arange(0, 10, 2)  # Crea un array de 0 a 10, con un paso de 2
print("Array con arange (0 a 10, paso 2):", array_arange)

# 2. Crear un array de ceros con `zeros`
# `zeros(shape)` crea un array lleno de ceros con la forma especificada.
array_zeros = np.zeros((3, 4))  # Crea un array de 3 filas y 4 columnas lleno de ceros
print("Array de ceros (3x4):\n", array_zeros)

# 3. Crear un array de unos con `ones`
# `ones(shape)` crea un array lleno de unos con la forma especificada.
array_ones = np.ones((2, 3))  # Crea un array de 2 filas y 3 columnas lleno de unos
print("Array de unos (2x3):\n", array_ones)

# 4. Crear un array con `linspace`
# `linspace(start, stop, num)` crea un array con un número especificado de puntos igualmente espaciados entre `start` y `stop`.
array_linspace = np.linspace(0, 1, 5)  # Crea un array de 5 valores entre 0 y 1
print("Array con linspace (0 a 1, 5 valores):", array_linspace)

# 5. Crear una matriz identidad con `eye`
# `eye(N)` crea una matriz identidad de tamaño N x N.
matriz_identidad = np.eye(3)  # Crea una matriz identidad de 3x3
print("Matriz identidad (3x3):\n", matriz_identidad)

Array con arange (0 a 10, paso 2): [0 2 4 6 8]
Array de ceros (3x4):
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Array de unos (2x3):
 [[1. 1. 1.]
 [1. 1. 1.]]
Array con linspace (0 a 1, 5 valores): [0.   0.25 0.5  0.75 1.  ]
Matriz identidad (3x3):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [51]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [55]:
np.zeros(3)

array([0., 0., 0.])

In [59]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [61]:
np.ones((6))

array([1., 1., 1., 1., 1., 1.])

In [63]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [79]:
np.linspace(3,9)

array([3.        , 3.12244898, 3.24489796, 3.36734694, 3.48979592,
       3.6122449 , 3.73469388, 3.85714286, 3.97959184, 4.10204082,
       4.2244898 , 4.34693878, 4.46938776, 4.59183673, 4.71428571,
       4.83673469, 4.95918367, 5.08163265, 5.20408163, 5.32653061,
       5.44897959, 5.57142857, 5.69387755, 5.81632653, 5.93877551,
       6.06122449, 6.18367347, 6.30612245, 6.42857143, 6.55102041,
       6.67346939, 6.79591837, 6.91836735, 7.04081633, 7.16326531,
       7.28571429, 7.40816327, 7.53061224, 7.65306122, 7.7755102 ,
       7.89795918, 8.02040816, 8.14285714, 8.26530612, 8.3877551 ,
       8.51020408, 8.63265306, 8.75510204, 8.87755102, 9.        ])

In [81]:
np.linspace(3,9,20) #indicamos comienzo, final y el numero de elementos 

array([3.        , 3.31578947, 3.63157895, 3.94736842, 4.26315789,
       4.57894737, 4.89473684, 5.21052632, 5.52631579, 5.84210526,
       6.15789474, 6.47368421, 6.78947368, 7.10526316, 7.42105263,
       7.73684211, 8.05263158, 8.36842105, 8.68421053, 9.        ])

In [83]:
np.eye(5) #filas

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [85]:
np.eye(5,3) #filas y columnas

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
import numpy as np  # Importar la biblioteca NumPy

# 1. Generar números aleatorios con `rand`
# `rand(dims)` genera números aleatorios en un rango de [0, 1) en la forma de un array con dimensiones especificadas.
array_rand = np.random.rand(3, 2)  # Crear un array de 3 filas y 2 columnas con números aleatorios
print("Array con números aleatorios (rand) de forma (3x2):\n", array_rand)

# 2. Generar números aleatorios con `randn`
# `randn(dims)` genera números aleatorios siguiendo una distribución normal estándar (media = 0, desviación estándar = 1).
array_randn = np.random.randn(3, 2)  # Crear un array de 3 filas y 2 columnas con números aleatorios de una normal
print("Array con números aleatorios (randn) de forma (3x2):\n", array_randn)

# 3. Generar un único número aleatorio entre 0 y 1 con `rand`
numero_aleatorio = np.random.rand()  # Generar un solo número aleatorio
print("Número aleatorio único (rand):", numero_aleatorio)

# 4. Generar un único número aleatorio con distribución normal con `randn`
numero_aleatorio_normal = np.random.randn()  # Generar un solo número aleatorio de una normal
print("Número aleatorio único (randn):", numero_aleatorio_normal)

Array con números aleatorios (rand) de forma (3x2):
 [[0.78899673 0.92642987]
 [0.54738598 0.26146595]
 [0.97901275 0.34693281]]
Array con números aleatorios (randn) de forma (3x2):
 [[ 0.48394687 -1.96672041]
 [ 1.22353202  1.03211974]
 [ 0.21626923 -1.37665122]]
Número aleatorio único (rand): 0.8519191803115891
Número aleatorio único (randn): -1.1620914840852155


In [94]:
np.random.rand(5)

array([0.29484677, 0.83425021, 0.76146517, 0.19124876, 0.68194795])

In [98]:
np.random.rand(2,3)

array([[0.10700248, 0.94362462, 0.20750149],
       [0.09171261, 0.90664366, 0.60043778]])

In [106]:
np.random.randn(4)

array([ 2.36518709, -0.84405995, -1.55086607,  0.8784092 ])

In [108]:
np.random.randn(4,5)

array([[ 1.5341621 ,  0.59495514, -1.99305828, -0.40726446,  0.82174827],
       [-0.28243   , -0.28691976,  2.09684724,  0.5954923 ,  0.87523577],
       [ 0.13127983, -0.2182441 ,  0.76584435,  1.7526879 ,  0.24985804],
       [-1.23000722, -0.46687093,  0.03933795,  0.15797473, -0.71924073]])

#Numpy arrays - numeros aleatorios enteros, randint

In [11]:
import numpy as np  # Importar la biblioteca NumPy

# 1. Generar números aleatorios enteros con `randint`
# `randint(low, high, size)` genera números enteros aleatorios en el rango [low, high).
# Aquí, 'low' es el límite inferior (incluido), 'high' es el límite superior (excluido) y 'size' es la forma del array.

# Generar un array de 5 números aleatorios enteros entre 0 y 10
array_randint = np.random.randint(0, 10, size=5)  # 5 enteros aleatorios entre 0 y 9
print("Array de números enteros aleatorios (randint):", array_randint)

# 2. Generar un array 2D de números aleatorios enteros
# Generar un array de 3 filas y 4 columnas con números aleatorios enteros entre 1 y 20
array_randint_2d = np.random.randint(1, 20, size=(3, 4))  # Enteros aleatorios entre 1 y 19
print("Array 2D de números enteros aleatorios (randint):\n", array_randint_2d)

# 3. Generar un solo número entero aleatorio
# Generar un único número entero aleatorio entre 0 y 100
numero_aleatorio_entero = np.random.randint(0, 100)  # Entero aleatorio entre 0 y 99
print("Número entero aleatorio único (randint):", numero_aleatorio_entero)

Array de números enteros aleatorios (randint): [7 2 5 1 0]
Array 2D de números enteros aleatorios (randint):
 [[ 9  4 14 15]
 [ 2  4  9  8]
 [ 9  1  3  6]]
Número entero aleatorio único (randint): 28


In [115]:
np.random.randint(1,20)

5

In [117]:
np.random.randint(1,20,5)

array([15,  2, 17,  4, 13])

#Numpy arrays - reshape

In [120]:
array = np.random.randint(1,100,21)

In [122]:
array

array([18,  2, 85, 59, 52,  8, 63, 43, 46, 23, 44, 38, 61, 63, 11, 95,  4,
        4, 77, 29, 32])

In [132]:
matriz = array.reshape(3,7)
print(matriz)

[[18  2 85 59 52  8 63]
 [43 46 23 44 38 61 63]
 [11 95  4  4 77 29 32]]


In [134]:
matriz2 = array.reshape(7,3)
print(matriz2)

[[18  2 85]
 [59 52  8]
 [63 43 46]
 [23 44 38]
 [61 63 11]
 [95  4  4]
 [77 29 32]]


#Numpy arrays - max y min

In [13]:
import numpy as np  # Importar la biblioteca NumPy

# Crear un array de números aleatorios
# Generar un array unidimensional de 10 números aleatorios enteros entre 0 y 100
array = np.random.randint(0, 100, size=10)  # Array de 10 enteros aleatorios
print("Array de números aleatorios:", array)

# 1. Encontrar el valor máximo
maximo = np.max(array)  # Encuentra el valor máximo en el array
print("Valor máximo del array:", maximo)

# 2. Encontrar el valor mínimo
minimo = np.min(array)  # Encuentra el valor mínimo en el array
print("Valor mínimo del array:", minimo)

# 3. Alternativa usando funciones de array
# También podemos usar las funciones .max() y .min() directamente en el array
maximo_alternativo = array.max()  # Usando el método max() del array
minimo_alternativo = array.min()  # Usando el método min() del array
print("Valor máximo (alternativa):", maximo_alternativo)
print("Valor mínimo (alternativa):", minimo_alternativo)

Array de números aleatorios: [74 33 85 39 63 50 18 64 84 90]
Valor máximo del array: 90
Valor mínimo del array: 18
Valor máximo (alternativa): 90
Valor mínimo (alternativa): 18


In [137]:
array = np.random.randint(1,100,50)

In [139]:
array

array([43,  9, 42, 63, 41, 82, 86, 55, 19, 52, 94, 35, 44, 24, 74, 29, 69,
        1, 41, 91, 40,  8, 68, 63, 65,  9, 48, 63, 52, 11, 98, 16, 41, 82,
        8, 95, 84, 94, 69, 81, 68, 87, 97, 17, 72, 83, 64, 51, 69, 35])

In [151]:
max = array.max()
posicion_max = array.argmax()
print(max)
print(posicion_max)
array[30] == 98

98
30


True

In [153]:
min = array.min()
posicion_min = array.argmin()
print(min)
print(posicion_min)
array[17] == 1

1
17


True

#Numpy - indexacion en arrays

In [15]:
import numpy as np  # Importar la biblioteca NumPy

# Crear un array unidimensional
array_1d = np.array([10, 20, 30, 40, 50])  # Crear un array unidimensional
print("Array unidimensional:", array_1d)

# Indexación en array unidimensional
print("Elemento en la posición 0:", array_1d[0])  # Acceder al primer elemento
print("Elemento en la posición 2:", array_1d[2])  # Acceder al tercer elemento
print("Último elemento:", array_1d[-1])           # Acceder al último elemento

# Crear un array bidimensional (matriz)
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  # Crear una matriz 3x3
print("\nArray bidimensional:\n", array_2d)

# Indexación en array bidimensional
print("Elemento en la fila 1, columna 2:", array_2d[1, 2])  # Acceder al elemento en la segunda fila y tercera columna
print("Elemento en la fila 0, columna 1:", array_2d[0, 1])  # Acceder al elemento en la primera fila y segunda columna

# Acceder a una fila completa
print("Fila 2 completa:", array_2d[2])  # Acceder a la tercera fila

# Acceder a una columna completa
print("Columna 1 completa:", array_2d[:, 1])  # Acceder a la segunda columna (todas las filas)

# Crear un array 3D
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])  # Crear un array tridimensional
print("\nArray tridimensional:\n", array_3d)

# Indexación en array tridimensional
print("Elemento en la posición (1, 0, 1):", array_3d[1, 0, 1])  # Acceder al elemento en el segundo bloque, primera fila, segunda columna

Array unidimensional: [10 20 30 40 50]
Elemento en la posición 0: 10
Elemento en la posición 2: 30
Último elemento: 50

Array bidimensional:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Elemento en la fila 1, columna 2: 6
Elemento en la fila 0, columna 1: 2
Fila 2 completa: [7 8 9]
Columna 1 completa: [2 5 8]

Array tridimensional:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Elemento en la posición (1, 0, 1): 6


In [162]:
array = np.arange(1,10)
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [164]:
array[0]

1

In [166]:
array[0:3]

array([1, 2, 3])

In [168]:
array[:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [170]:
array[2:]

array([3, 4, 5, 6, 7, 8, 9])

In [172]:
array[:5]

array([1, 2, 3, 4, 5])

In [176]:
array2 = array.copy()
array2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [178]:
array2[0]=100
array2

array([100,   2,   3,   4,   5,   6,   7,   8,   9])

In [180]:
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

#Numpy - indexacion en arrays de 2 o mas dimensiones

In [17]:
import numpy as np  # Importar la biblioteca NumPy

# Crear un array bidimensional (matriz)
array_2d = np.array([[10, 20, 30], 
                     [40, 50, 60], 
                     [70, 80, 90]])  # Crear una matriz 3x3
print("Array bidimensional:\n", array_2d)

# 1. Acceder a un elemento específico
# Acceder al elemento en la segunda fila y tercera columna (índices 1, 2)
elemento_especifico = array_2d[1, 2]
print("Elemento en la fila 1, columna 2:", elemento_especifico)  # 60

# 2. Acceder a una fila completa
# Acceder a la primera fila (índice 0)
fila_1 = array_2d[0]
print("Primera fila:", fila_1)  # [10, 20, 30]

# 3. Acceder a una columna completa
# Acceder a la segunda columna (índice 1)
columna_2 = array_2d[:, 1]  # ':' significa "todas las filas"
print("Segunda columna:", columna_2)  # [20, 50, 80]

# 4. Slicing (rebanado) de un array bidimensional
# Acceder a un sub-array que incluye la primera y segunda fila, y la primera y segunda columna
sub_array = array_2d[0:2, 0:2]  # Primeras dos filas y primeras dos columnas
print("Sub-array:\n", sub_array)

# 5. Crear un array tridimensional
array_3d = np.array([[[1, 2], [3, 4]], 
                      [[5, 6], [7, 8]], 
                      [[9, 10], [11, 12]]])  # Crear un array 3D
print("\nArray tridimensional:\n", array_3d)

# 6. Acceder a un elemento específico en un array tridimensional
# Acceder al elemento en el primer bloque, segunda fila, segunda columna (índices 0, 1, 1)
elemento_3d = array_3d[0, 1, 1]
print("Elemento en el bloque 0, fila 1, columna 1:", elemento_3d)  # 4

# 7. Acceder a un bloque completo
# Acceder al primer bloque (índice 0)
bloque_0 = array_3d[0]
print("Primer bloque:\n", bloque_0)

# 8. Slicing en un array tridimensional
# Acceder a un sub-array que incluye todos los bloques, primera fila y columnas
sub_array_3d = array_3d[:, 0, :]  # Todas las filas de la primera fila y todas las columnas
print("Sub-array 3D:\n", sub_array_3d)

Array bidimensional:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]
Elemento en la fila 1, columna 2: 60
Primera fila: [10 20 30]
Segunda columna: [20 50 80]
Sub-array:
 [[10 20]
 [40 50]]

Array tridimensional:
 [[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
Elemento en el bloque 0, fila 1, columna 1: 4
Primer bloque:
 [[1 2]
 [3 4]]
Sub-array 3D:
 [[ 1  2]
 [ 5  6]
 [ 9 10]]


In [187]:
array[0]

array([1, 2, 3])

In [189]:
array[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [191]:
array[0][2] 

3

In [195]:
array[0,2]

3

In [203]:
array[:,0]

array([1, 4, 7])

In [205]:
array[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

#Numpy - seleccionar elementos de una array segun una condicion

In [19]:
import numpy as np  # Importar la biblioteca NumPy

# Crear un array unidimensional de números aleatorios
array = np.array([1, 5, 8, 12, 20, 25, 30, 35])  # Crear un array de enteros
print("Array original:", array)

# 1. Seleccionar elementos mayores que 10
condicion_mayor_10 = array[array > 10]  # Filtrar elementos mayores que 10
print("Elementos mayores que 10:", condicion_mayor_10)

# 2. Seleccionar elementos pares
condicion_pares = array[array % 2 == 0]  # Filtrar elementos que son pares
print("Elementos pares:", condicion_pares)

# 3. Seleccionar elementos que son mayores que 10 y menores que 30
condicion_rango = array[(array > 10) & (array < 30)]  # Filtrar elementos en el rango (10, 30)
print("Elementos mayores que 10 y menores que 30:", condicion_rango)

# 4. Crear un array bidimensional
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])  # Crear una matriz 3x3
print("\nArray bidimensional:\n", array_2d)

# 5. Seleccionar elementos mayores que 5 en un array bidimensional
condicion_mayor_5_2d = array_2d[array_2d > 5]  # Filtrar elementos mayores que 5
print("Elementos mayores que 5 en el array 2D:\n", condicion_mayor_5_2d)

# 6. Seleccionar elementos en la primera fila que son mayores que 2
condicion_fila_1 = array_2d[0, array_2d[0] > 2]  # Filtrar elementos en la primera fila mayores que 2
print("Elementos en la primera fila mayores que 2:", condicion_fila_1)

# 7. Seleccionar todos los elementos que son mayores que 2 en todo el array
condicion_mayor_2 = array_2d[array_2d > 2]  # Filtrar elementos mayores que 2
print("Elementos mayores que 2 en el array 2D:\n", condicion_mayor_2)

Array original: [ 1  5  8 12 20 25 30 35]
Elementos mayores que 10: [12 20 25 30 35]
Elementos pares: [ 8 12 20 30]
Elementos mayores que 10 y menores que 30: [12 20 25]

Array bidimensional:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Elementos mayores que 5 en el array 2D:
 [6 7 8 9]
Elementos en la primera fila mayores que 2: [3]
Elementos mayores que 2 en el array 2D:
 [3 4 5 6 7 8 9]


In [21]:
array = np.arange(0,10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
condicion = array > 5
condicion

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [216]:
array[condicion]

array([6, 7, 8, 9])

In [218]:
array[array > 5]

array([6, 7, 8, 9])

In [220]:
array[array % 2 == 0]

array([0, 2, 4, 6, 8])

#Numpy - Operaciones con Array

In [223]:
array = np.arange(0,10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [225]:
array + array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [227]:
array * array

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [229]:
array - array

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [231]:
array + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [233]:
np.sqrt(array)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

#Ejercicio 1

Crea una lista de números secuenciales con el valor mínimo de 10 y el valor máximo 39
Convierte esta lista en una lista o matriz de 2 dimensiones (3 filas y 10 columnas)
Muestra por pantalla el valor del elemento de la esquina superior derecha de la matriz

In [248]:
lista = np.arange(10, 40)

In [250]:
lista2 = lista.reshape(3,10)

In [252]:
lista2[0][-1] 

19

#Ejercicio 1

Crear un array que tenga 9 valores enteros aleatorios entre 0 y 100
Convierte ese array en una matriz de dos dimension (3 filas y 3 columnas)
Muestra por pantalla el valor del elemento de la matriz, de la esquina inferior derecha

In [258]:
array = np.random.randint(0,100,9)

In [262]:
matriz = array.reshape(3,3)
matriz

array([[77, 31, 56],
       [20, 46, 85],
       [13, 90,  7]])

In [272]:
matriz[-1][-1]

7

In [ ]:
Ejercicio3

In [274]:
import numpy as np

def generar_numeros_enteros_aleatorios(N, minimo, maximo):
    return list(np.random.randint(minimo, maximo + 1, N))


In [278]:
N=20
minimo = 1
maximo = 10
resultado = generar_numeros_enteros_aleatorios(N, minimo, maximo)
print(resultado)

[7, 5, 4, 8, 4, 4, 5, 5, 1, 9, 5, 2, 2, 9, 3, 2, 10, 5, 9, 2]


Ejecicio 3

In [283]:
import numpy as np

def generar_secuencia_numerica(minimo, maximo, paso):
    return np.arange(minimo, maximo, paso)

In [285]:
minimo = 0
maximo = 10
paso = 2
resultado = generar_secuencia_numerica(minimo, maximo, paso)
print(resultado)          
print(type(resultado))

[0 2 4 6 8]
<class 'numpy.ndarray'>
