In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
pwd

'C:\\Users\\roman\\Programa IA IBM\\Curso\\Sesiónes\\ML'

In [5]:
cd Material13


C:\Users\roman\Programa IA IBM\Curso\Sesiónes\ML\Material13


In [7]:
ls

 El volumen de la unidad C no tiene etiqueta.
 El n£mero de serie del volumen es: F29B-042F

 Directorio de C:\Users\roman\Programa IA IBM\Curso\Sesi¢nes\ML\Material13

03/11/2024  00:58    <DIR>          .
03/11/2024  01:01    <DIR>          ..
03/11/2024  00:40    <DIR>          .ipynb_checkpoints
03/11/2024  00:58            10.137 algoritmo-de-clasificacion.ipynb
03/11/2024  00:35               719 arboles_de_decision.py
03/11/2024  00:35            12.895 vino.csv
               3 archivos         23.751 bytes
               3 dirs  387.001.221.120 bytes libres


In [9]:
vinos= pd.read_csv("vino.csv")
vinos.head()

Alcohol  Malic acid   Ash  Alcalinity of ash  Magnesium  Total phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   Flavanoids  Nonflavanoid phenols  Proanthocyanins  Color intensity   Hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   OD280/OD315 of diluted wines  Proline Wine Type  
0                          3.92   1065.0       One  
1                          3.40   1050.0       One  
2                          3.17   1185.0       One  
3                          3.45   1480.0       One  
4                          2.93    735.0       One

In [15]:
X = vinos.drop("Wine Type", axis=1)
y = vinos["Wine Type"]

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [19]:
from sklearn.ensemble import RandomForestClassifier

In [21]:
randomforest = RandomForestClassifier(n_estimators=80)

In [23]:
randomforest.fit(X_train, y_train)

RandomForestClassifier(n_estimators=80)

In [25]:
predicciones = randomforest.predict(X_test)

In [27]:
predicciones

array(['Three', 'Three', 'Three', 'One', 'Two', 'Two', 'Two', 'Three',
       'Two', 'Two', 'Three', 'Two', 'Three', 'One', 'One', 'Two', 'Two',
       'Two', 'Two', 'Two', 'Two', 'Two', 'One', 'Two', 'Two', 'One',
       'Three', 'Two', 'Three', 'Two', 'Two', 'One', 'Two', 'Three',
       'Two', 'One', 'Two', 'Two', 'One', 'Three', 'One', 'One', 'Two',
       'One', 'One', 'One', 'Three', 'Two', 'Three', 'Three', 'One',
       'Two', 'Two', 'Three'], dtype=object)

In [29]:
from sklearn.metrics import classification_report, confusion_matrix

In [31]:
print(classification_report(y_test, predicciones))

              precision    recall  f1-score   support

         One       1.00      1.00      1.00        14
       Three       0.86      1.00      0.92        12
         Two       1.00      0.93      0.96        28

    accuracy                           0.96        54
   macro avg       0.95      0.98      0.96        54
weighted avg       0.97      0.96      0.96        54



In [33]:
print(confusion_matrix(y_test, predicciones))

[[14  0  0]
 [ 0 12  0]
 [ 0  2 26]]
