In [4]:
#Matriz con datos de ejercicio dado

import numpy as np
temporadas = ["2005","2006","2007","2008","2009","2010","2011","2012","2013","2014"]
dic_temp = {"2005":0,"2006":1,"2007":2,"2008":3,"2009":4,"2010":5,"2011":6,"2012":7,"2013":8,"2014":9}

#Jugadores
jugadores = ["KobeBryant","JoeJohnson","LeBronJames","CarmeloAnthony","DwightHoward","ChrisBosh","ChrisPaul","KevinDurant","DerrickRose","DwayneWade"]
dic_jug = {"KobeBryant":0,"JoeJohnson":1,"LeBronJames":2,"CarmeloAnthony":3,"DwightHoward":4,"ChrisBosh":5,"ChrisPaul":6,"KevinDurant":7,"DerrickRose":8,"DwayneWade":9}

#Sueldo
KobeBryant_sueldo = [15946875,17718750,19490625,21262500,23034375,24806250,25244493,27849149,30453805,23500000]
JoeJohnson_sueldo = [12000000,12744189,13488377,14232567,14976754,16324500,18038573,19752645,21466718,23180790]
LeBronJames_sueldo = [4621800,5828090,13041250,14410581,15779912,14500000,16022500,17545000,19067500,20644400]
CarmeloAnthony_sueldo = [3713640,4694041,13041250,14410581,15779912,17149243,18518574,19450000,22407474,22458000]
DwightHoward_sueldo = [4493160,4806720,6061274,13758000,15202590,16647180,18091770,19536360,20513178,21436271]
ChrisBosh_sueldo = [3348000,4235220,12455000,14410581,15779912,14500000,16022500,17545000,19067500,20644400]
ChrisPaul_sueldo = [3144240,3380160,3615960,4574189,13520500,14940153,16359805,17779458,18668431,20068563]
KevinDurant_sueldo = [0,0,4171200,4484040,4796880,6053663,15506632,16669630,17832627,18995624]
DerrickRose_sueldo = [0,0,0,4822800,5184480,5546160,6993708,16402500,17632688,18862875]
DwayneWade_sueldo = [3031920,3841443,13041250,14410581,15779912,14200000,15691000,17182000,18673000,15000000]
#Matriz
sueldo = np.array([KobeBryant_sueldo, JoeJohnson_sueldo, LeBronJames_sueldo, CarmeloAnthony_sueldo, DwightHoward_sueldo, ChrisBosh_sueldo, ChrisPaul_sueldo, KevinDurant_sueldo, DerrickRose_sueldo, DwayneWade_sueldo])


In [13]:
print(sueldo)

[[15946875 17718750 19490625 21262500 23034375 24806250 25244493 27849149
  30453805 23500000]
 [12000000 12744189 13488377 14232567 14976754 16324500 18038573 19752645
  21466718 23180790]
 [ 4621800  5828090 13041250 14410581 15779912 14500000 16022500 17545000
  19067500 20644400]
 [ 3713640  4694041 13041250 14410581 15779912 17149243 18518574 19450000
  22407474 22458000]
 [ 4493160  4806720  6061274 13758000 15202590 16647180 18091770 19536360
  20513178 21436271]
 [ 3348000  4235220 12455000 14410581 15779912 14500000 16022500 17545000
  19067500 20644400]
 [ 3144240  3380160  3615960  4574189 13520500 14940153 16359805 17779458
  18668431 20068563]
 [       0        0  4171200  4484040  4796880  6053663 15506632 16669630
  17832627 18995624]
 [       0        0        0  4822800  5184480  5546160  6993708 16402500
  17632688 18862875]
 [ 3031920  3841443 13041250 14410581 15779912 14200000 15691000 17182000
  18673000 15000000]]


In [15]:
sueldo[0,0]

15946875

In [17]:
sueldo [0,:]

array([15946875, 17718750, 19490625, 21262500, 23034375, 24806250,
       25244493, 27849149, 30453805, 23500000])

In [19]:
sueldo[:,0]

array([15946875, 12000000,  4621800,  3713640,  4493160,  3348000,
        3144240,        0,        0,  3031920])

In [23]:
misdatos = np.arange(0,20)
print(misdatos)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [63]:
np.reshape(misdatos, (5,4))#default es opuesto a R

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [65]:
matr1=np.reshape(misdatos, (5,4), order="C")
print(matr1)
matr1[4,2]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


18

In [75]:
matr2=np.reshape(misdatos, (5,4), order="F")
print(matr2)
print(matr2[4,2])
print(matr2[3,3])

[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]
14
18


In [81]:
#Concepto de POO
#matr2=np.reshape(misdatos, (5,4), order="F")
#print(matr2)
type(misdatos)

numpy.ndarray

In [83]:
misdatos.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [89]:
misdatos[0]=100

In [91]:
misdatos.reshape(5,4)

array([[100,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11],
       [ 12,  13,  14,  15],
       [ 16,  17,  18,  19]])

In [93]:
r1 = ["Soy", "muy", "feliz"]
r2 = ["Que", "gran", "dia"]
r3 = [1, 2, 3]
[r1, r2, r3]

[['Soy', 'muy', 'feliz'], ['Que', 'gran', 'dia'], [1, 2, 3]]

In [95]:
np.array([r1, r2, r3])

array([['Soy', 'muy', 'feliz'],
       ['Que', 'gran', 'dia'],
       ['1', '2', '3']], dtype='<U11')

In [97]:
print([r1, r2, r3])

[['Soy', 'muy', 'feliz'], ['Que', 'gran', 'dia'], [1, 2, 3]]


In [99]:
sueldo

array([[15946875, 17718750, 19490625, 21262500, 23034375, 24806250,
        25244493, 27849149, 30453805, 23500000],
       [12000000, 12744189, 13488377, 14232567, 14976754, 16324500,
        18038573, 19752645, 21466718, 23180790],
       [ 4621800,  5828090, 13041250, 14410581, 15779912, 14500000,
        16022500, 17545000, 19067500, 20644400],
       [ 3713640,  4694041, 13041250, 14410581, 15779912, 17149243,
        18518574, 19450000, 22407474, 22458000],
       [ 4493160,  4806720,  6061274, 13758000, 15202590, 16647180,
        18091770, 19536360, 20513178, 21436271],
       [ 3348000,  4235220, 12455000, 14410581, 15779912, 14500000,
        16022500, 17545000, 19067500, 20644400],
       [ 3144240,  3380160,  3615960,  4574189, 13520500, 14940153,
        16359805, 17779458, 18668431, 20068563],
       [       0,        0,  4171200,  4484040,  4796880,  6053663,
        15506632, 16669630, 17832627, 18995624],
       [       0,        0,        0,  4822800,  5184480,  55461

In [101]:
sueldo[2]

array([ 4621800,  5828090, 13041250, 14410581, 15779912, 14500000,
       16022500, 17545000, 19067500, 20644400])

In [107]:
sueldo[2][9]

20644400

In [118]:
sueldo[2][-1]

20644400

In [124]:
sueldo[2,-1]

20644400

---

In [127]:
dicc1 = {"clave1":"valor1", 'clave2':'valor2', "clave3":"valor3"}

In [129]:
dicc1

{'clave1': 'valor1', 'clave2': 'valor2', 'clave3': 'valor3'}

In [131]:
dicc1["clave1"]

'valor1'

In [139]:
dicc2 = {"España":"valor de España", 'ocupacion':True, "poblacion":300}

In [141]:
dicc2

{'España': 'valor de España', 'ocupacion': True, 'poblacion': 300}

In [8]:
print(sueldo)

[[15946875 17718750 19490625 21262500 23034375 24806250 25244493 27849149
  30453805 23500000]
 [12000000 12744189 13488377 14232567 14976754 16324500 18038573 19752645
  21466718 23180790]
 [ 4621800  5828090 13041250 14410581 15779912 14500000 16022500 17545000
  19067500 20644400]
 [ 3713640  4694041 13041250 14410581 15779912 17149243 18518574 19450000
  22407474 22458000]
 [ 4493160  4806720  6061274 13758000 15202590 16647180 18091770 19536360
  20513178 21436271]
 [ 3348000  4235220 12455000 14410581 15779912 14500000 16022500 17545000
  19067500 20644400]
 [ 3144240  3380160  3615960  4574189 13520500 14940153 16359805 17779458
  18668431 20068563]
 [       0        0  4171200  4484040  4796880  6053663 15506632 16669630
  17832627 18995624]
 [       0        0        0  4822800  5184480  5546160  6993708 16402500
  17632688 18862875]
 [ 3031920  3841443 13041250 14410581 15779912 14200000 15691000 17182000
  18673000 15000000]]


In [10]:
dic_jug["KobeBryant"]

0